# Generated by Django 5.1.7 on 2025-03-26 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('farm_name', models.CharField(max_length=200)),
                ('site_name', models.CharField(max_length=200)),
                ('hen_house_number', models.CharField(max_length=50)),
                ('current_number_of_hens', models.PositiveIntegerField()),
                ('average_age_weeks', models.FloatField()),
                ('breed', models.CharField(choices=[('LEGHORN', 'Leghorn'), ('RHODE_ISLAND_RED', 'Rhode Island Red'), ('PLYMOUTH_ROCK', 'Plymouth Rock'), ('AUSTRALORP', 'Australorp'), ('ORPINGTON', 'Orpington'), ('OTHER', 'Other')], max_length=50)),
                ('breed_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('daily_egg_production', models.FloatField(help_text='Daily egg production in dozens')),
                ('weekly_egg_production', models.FloatField(help_text='Weekly egg production in dozens')),
                ('small_eggs_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('medium_eggs_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('large_eggs_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('extra_large_eggs_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('jumbo_eggs_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('defective_eggs_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('first_grade_egg_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_feed_consumption', models.FloatField(help_text='Average feed consumption in g/hen/day')),
                ('average_water_intake', models.FloatField(help_text='Average water intake in L/hen/day')),
                ('weekly_mortality_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_mortality', models.PositiveIntegerField()),
                ('hens_culled', models.PositiveIntegerField()),
                ('expected_cull_date', models.DateField(blank=True, null=True)),
                ('recent_placement_date', models.DateField(blank=True, null=True)),
                ('age_of_pullets_at_placement', models.FloatField(blank=True, null=True)),
                ('upcoming_placement_date', models.DateField(blank=True, null=True)),
                ('health_issues', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('recent_vaccinations', models.TextField(blank=True, null=True)),
                ('next_vaccination_date', models.DateField(blank=True, null=True)),
                ('time_to_distribution', models.PositiveIntegerField(help_text='Time from egg collection to distribution (days)')),
                ('market_condition_notes', models.TextField(blank=True, null=True)),
                ('weekly_production_trend', models.FloatField(help_text='Weekly production trend (%) compared to last week')),
                ('seasonal_trend_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egg Farm Record',
                'verbose_name_plural': 'Egg Farm Records',
                'unique_together': {('farm_name', 'site_name', 'hen_house_number')},
            },
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
