# Generated by Django 5.1.7 on 2025-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eggfarm_delete_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggfarm',
            name='production_date',
            field=models.DateField(blank=True, help_text='Date representing the week of production', null=True),
        ),
    ]
