# Generated by Django 5.1.7 on 2025-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eggfarm_production_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eggfarm',
            unique_together={('farm_name', 'site_name', 'hen_house_number', 'production_date')},
        ),
        migrations.AddIndex(
            model_name='eggfarm',
            index=models.Index(fields=['production_date'], name='main_eggfar_product_162f47_idx'),
        ),
        migrations.AddIndex(
            model_name='eggfarm',
            index=models.Index(fields=['farm_name', 'site_name', 'hen_house_number'], name='main_eggfar_farm_na_47c87e_idx'),
        ),
    ]
